# Generated by Django 6.1.1 on 2026-10-06 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current available units in this batch')),
                ('initial_quantity', models.PositiveIntegerField(default=0, help_text='Original received units')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='medicines.medicine')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PURCHASE_RECEIVE', 'Stock Received'), ('SALE_DEDUCTION', 'Sale Deduction (FEFO)'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('DISPOSAL_EXPIRED', 'Disposal of Expired Stock'), ('RETURN_RESTOCK', 'Return Restocked')], max_length=30)),
                ('quantity_change', models.IntegerField(help_text='Positive for addition, negative for reduction')),
                ('previous_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, help_text='e.g. Invoice # or PO #', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.batch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
