# Generated by Django 6.1.1 on 2026-10-06 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['medicine', 'expiry_date', 'quantity'], name='inventory_b_medicin_b01d49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_number', 'medicine')},
        ),
    ]
