# Generated by Django 6.1.1 on 2026-10-06 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('generic_name', models.CharField(db_index=True, max_length=200)),
                ('brand', models.CharField(db_index=True, max_length=150)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('OTHER', 'Other')], default='TABLET', max_length=30)),
                ('strength', models.CharField(help_text='e.g. 500mg, 250mg/5ml', max_length=100)),
                ('prescription_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Threshold for low-stock alert')),
                ('maximum_stock', models.PositiveIntegerField(default=500, help_text='Ceiling for overstock alert')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicines.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'generic_name'], name='medicines_m_name_c269a0_idx'), models.Index(fields=['brand'], name='medicines_m_brand_9540c8_idx')],
            },
        ),
    ]
